version: "3.9"

services:
  discord-bot:
    build: .
    container_name: teambridge-bot
    restart: always
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; print('ok')"]
      interval: 30s
      timeout: 5s
      retries: 3
